import {Component} from 'angular2/core';

@Component({
    selector: 'course-comp',
    templateUrl: 'app/block.component.html'
})
export class CourseComponent {
    jump_id = "cource";
    title = "Tutoring!";
    paragraphs = [
        "INLEIDING",
        "Bij tutoring is het de bedoeling dat tweede of derde jaars studenten tutoring of te wel bijles gaan geven aan eerste jaars studenten. Ik leg wel graag dingen uit aan mijn medestudenten in de les. Daarom heb ik voor deze activiteit gekozen.",
        "VERSLAG",
        "Bij tutoring is het de bedoeling dat je drie bijlessen van twee uur geeft. Verspreid over de duur van het vak. Je krijgt er als tutor één of meerdere studenten toegewezen voor één bepaald vak. Hierna heb je de volledige vrijheid en verantwoordelijkheid om deze lessen in te plan en te geven. Je mag ze geven hou je wil, waar je wil, en wanneer je wil. Ook moet je voor elke les een voorbereiding maken en de leerstof van het afgelopen jaar terug herhalen. Je krijgt ook feedback op je les voorbereiding. Op die manier leer je snel bij en word je toch niet helemaal voor de leeuwen gegooit. Na afloop van de les schrijf je een kort reflexie verslag over zowel je tutee als jezelf. Dit is belangrijk omdat je moet focussen op de pijn punten van de tutee en op jou eigen valkuilen. En dit niet enkel op vlak van de leerstof maar ook over jou als persoon. Bijvoorbeeld, sommige tutee's begrijpen heel goed de theorie, maar hebben moeite met de oefeningen. Dan heeft het weinig nut om verder de theorie uit te leggen, maar moet je actie ondernemen en zoeken waar het probleem ligt bij oefeningen.",
        "Ik zelf heb tutoring gegeven in drie verschillende vakken en met vier verschillende tutee's. Programming basic's , Java essentials en Math for IT. Programming basic's is een vak waarin de basis van programeren en logica word uitgelegd. Dit gebeurd allemaal aan de hand van kleine oefeningen in Java. Er wordt ondermeer uitgelegd hoe een For-lus werkt, hoe een If statement zich gedraagt en hoe variable werken. Dit is volledig imperatief programeren. Java Essentials gaat hier op verder. Bij dit vak komen de basics aan bod van Object georienteerd programeren en een eenvoudige GUI maken met Swing. Het Object georienteerd programeren is voor vele een groot struikel blok! Hier had ik ook twee tutee's bij. In Math for IT zit vector rekenen, logische vergelijkingen en matrix omvormingen. Ook dit vak is voor velen een struikel blok.de combinatie van de lange duur van dit vak, en de moeilijkheids graag zorden ervoor dat ik dit vak in plaats van 6 uur, 12 uur heb gegeven.",
        "De tutee's van deze drie vakken waren zeer uiteenlopend op vlak van persoonlijkheid en achtergrond! Voor programming basic's had ik een tutee die al eerder universiteit had geprobeerd en hierna naar bij ons kwam. Wat mij opviel aan hem was het feit dat hij weinig durfde. In de zin dat hij altijd vroeg een oefening voor te maken in plaats van deze zelf te proberen. Ook tijdens het zelf maken van een oefening, wanneer hij twijfelde stopte hij. Hij had schrik om fouten te maken. Bij Java essentials had ik 2 tutee's. Beide heel verschillend. De eerste was relatief stil en zei op alles:\"ja ik snap het\" en stelde in de meeste gevallen ook geen vragen. Zijn examen ging echer niet zo goed. De tweede was zeer interessant, in het middelbaar houtbewerking BSO gevolgt, daarna een zevende jaar. Toen zeiden de meesten al dat het hem nooit zou lukken. Geslaagd en IT gaan studeren. Waarvan opnieuw zeer veel mensen in zijn omgeving verwachten dat hij niet zou slagen. Hij is echter in zijn eerste jaar op alles geslaagt in eerste zit. Mijn laatste tutee van Math for IT was opnieuw een ander verhaal. Hij was bijna dertig, had een appertement en had ook al 10 jaar gewerkt. Waarom kwam hij dan toch terug verder studeren? Quote:\"Tom... Werk dat ge nie graag doet... IS GODVERDOME FRUSTREREND!\". ",
        "REFLECTIE",
        "Wat heb ik hier allemaal uit geleerd? Om te beginnen dat er meer dan enkel wat verstand nodig is om te slagen in je studie of eenderwelk doel je ook voor ogen hebt. Motivatie, attitude, durven fouten maken en zelf actie ondernemen en vragen stellen. De durf om fouten misten mijn eerste tutee. Hierdoor maakte hij zijn oefeningen niet af, en probeerde hij niet. Attitude zorgde er bij mijn tweede tutee voor dat hij met een BSO richting als basis er volledig voor ging in het hoger onderwijs. En wat hem er dus uiteindelijk in liet slagen om over de volledige lijn te slagen in zijn eerste jaar. Initiatief nemen om ergens aan te beginnen om zijn problemen zelf op te lossen of om hulp te vragen, miste mijn 3de tutee. En motivattie en doorzettings vermogen maake dat mijn tutee van Math for IT Er volledig voor ging.",
        "Ik had niet verwacht dat er zoveel tijd nodig was omeen les in orde te brengen. De lesuren regelen, les voorbereiding maken, lokaal reserveren, ... nam allemaal veel meer tijd in beslag dan dat ik oorspronkelijk had verwacht. Ook het les geven zelf was vermoeidere dan oorsprokelijk gedacht. Je moet er altijd bij zijn, alles uitleggen, en opnieuw en een voorbeeld verzinnen, ... Ook moet je vaak naar het diepere probleem zoeken. Stel dat mijn tutee zegt dat hij de theorie wel begrijpt maar de oefeningen niet lukken, zou het eventueel toch de oorzaak kunnen zijn van gebrek aan kennis over de theorie. Of dat je bijvoorbeeld iets verkeerd zou hebben opgevat van de theorie. Het was ook zeer interessant om te zien hoe je bepaalde mensen kon triggeren. sommige moest je kleine details verduidelijken, andere moest je veel misvattingen verhelpen en nog anderen kon je helpen door iets zeer abstract uit te leggen aan de hand van een simpel voorbeeld van een boer met witte kool."
    ];
}
