import {bootstrap}    from 'angular2/platform/browser';
import {NavComponent} from './nav.component';
import {WhoisheComponent} from './whoishe.component';
import {ImagestrapComponent} from './imagestrap.component';
import {SkillComponent} from './skill.component';
import {OverviewComponent} from './overview.component';
import {AWSComponent} from './amazone.component';
import {CebitComponent} from './cebit.component';
import {CourseComponent} from './course.component';
import {INGComponent} from './ing.component';
import {ReflectionComponent} from './reflection.component';

bootstrap(NavComponent);
bootstrap(WhoisheComponent);
bootstrap(ImagestrapComponent);
bootstrap(SkillComponent);
bootstrap(OverviewComponent);
bootstrap(AWSComponent);
bootstrap(CebitComponent);
bootstrap(CourseComponent);
bootstrap(INGComponent);
bootstrap(ReflectionComponent);
